"""sync_manufacturing_steps_schema

Revision ID: fa63140935ab
Revises: 001_initial_complete_schema
Create Date: 2025-11-22 16:12:52.191177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa63140935ab'
down_revision = '001_initial_complete_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # These columns were never created in 001_initial_complete_schema, so skip dropping them
    # op.alter_column('manufacturing_steps', 'step_type',
    #            existing_type=postgresql.ENUM('DESIGN', 'CASTING', 'STONE_SETTING', 'POLISHING', 'ENGRAVING', 'QUALITY_CHECK', 'FINISHING', 'OTHER', name='steptype'),
    #            nullable=True)
    # op.alter_column('manufacturing_steps', 'step_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.drop_column('manufacturing_steps', 'weight_loss_percentage')
    # op.drop_column('manufacturing_steps', 'expected_loss_percentage')
    # op.drop_column('manufacturing_steps', 'weight_loss')
    # op.drop_column('manufacturing_steps', 'sequence_order')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op since upgrade is also no-op
    pass
    # ### end Alembic commands ###
