AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Secrets Manager secrets for jewelry manufacturing application'

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    AllowedValues: [dev, staging, prod]
    Default: "dev"
  
  DatabaseUrl:
    Type: String
    Description: PostgreSQL database URL
    NoEcho: true
    Default: "postgresql://user:password@localhost:5432/jewelry_manufacturing"
  
  JwtSecretKey:
    Type: String
    Description: JWT secret key for token signing
    NoEcho: true
    Default: "your-jwt-secret-key-change-this-in-production"
  
  CorsOrigins:
    Type: String
    Description: Comma-separated list of allowed CORS origins
    Default: "http://localhost:5173,https://your-domain.com"

Resources:
  # Main application secrets
  ApplicationSecrets:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub "jewelry-manufacturing-${Environment}"
      Description: !Sub "Application secrets for jewelry manufacturing ${Environment} environment"
      KmsKeyId: alias/aws/secretsmanager
      SecretString: !Sub |
        {
          "DATABASE_URL": "${DatabaseUrl}",
          "JWT_SECRET_KEY": "${JwtSecretKey}",
          "CORS_ORIGINS": "${CorsOrigins}",
          "ENVIRONMENT": "${Environment}"
        }
      Tags:
        - Key: Name
          Value: !Sub "jewelry-manufacturing-secrets-${Environment}"
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: "jewelry-manufacturing"

  # Resource policy to allow GitHub Actions access while preserving management capabilities
  SecretsResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref ApplicationSecrets
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAccountRootFullAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "secretsmanager:*"
            Resource: "*"
          - Sid: AllowGitHubActionsReadAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:role/github-actions-${Environment}"
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: "*"

Outputs:
  SecretArn:
    Description: ARN of the application secrets
    Value: !Ref ApplicationSecrets
    Export:
      Name: !Sub "${AWS::StackName}-SecretArn"
  
  SecretName:
    Description: Name of the application secrets
    Value: !Sub "jewelry-manufacturing-${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-SecretName"